fix issue with en-IE currency
BenjaminVanRyseghem/numbro pull request #569
Opened 2020-09-09 21:32 UTC by Blackbaud-WesGabbard

Ran into issue when trying to format currency for Ireland. When setting culture as en-IE was getting the following error:

`Currency position should be among ["prefix", "infix", "postfix"]`

Looking at the en-IE.js file in the languages folder, it is missing a property defining the position of the currency symbol. Added this to be prefix since Euro symbols go in front. Updated the test to account for this.

2020-09-18 15:24 UTC, Blackbaud-WesGabbard commented
@BenjaminVanRyseghem, just checking in on this PR and see if there is anything else needed on my end. Thanks.

2020-10-15 19:29 UTC, Blackbaud-WesGabbard commented
@BenjaminVanRyseghem checking in on this PR, is there any reason this can't be merged? Would like to be able to format currency for Ireland and in its current state I am not able using this library. This is fairly small update that should resolve the issue. Thanks.

2020-10-15 19:43 UTC, BenjaminVanRyseghem commented
Sorry, I am **very** busy right now, I actually have an epic deadline next thursday...

I'll have a look as soon as I have 5' :smile:

Sorry for the inconvenience

2021-02-03 13:15 UTC, Blackbaud-WesGabbard commented
@BenjaminVanRyseghem, can this PR be merged? Thanks

2021-02-03 13:18 UTC, BenjaminVanRyseghem requested changes

2021-02-03 13:18 UTC, BenjaminVanRyseghem commented on CHANGELOG.md
> +- Fix issue with en-IE currency by adding currency position of `prefix`
wrong format

2021-02-03 13:18 UTC, BenjaminVanRyseghem commented on AUTHORS
> +Wes Gabbard (https://github.com/Blackbaud-WesGabbard)
Move it to another commit please, so that possibly reverting your code won't remove you from the authors list :smile:

2021-02-03 13:19 UTC, BenjaminVanRyseghem commented
do you have any documentation showing that the currency is prefix? (to avoid another PR tomorrow to change it as it happened already :smile:) 

Sorry for the delay, and thanks for the PR

2021-02-03 14:33 UTC, Blackbaud-WesGabbard commented on CHANGELOG.md
> +- Fix issue with en-IE currency by adding currency position of `prefix`
Sorry about that, pushed change to add PR #

2021-02-03 14:33 UTC, Blackbaud-WesGabbard commented on AUTHORS
> +Wes Gabbard (https://github.com/Blackbaud-WesGabbard)
Done

2021-02-03 14:37 UTC, Blackbaud-WesGabbard commented
Hey @BenjaminVanRyseghem,
Understand completely. From my understanding the Euro sign placement depends on the country/language. English language countries put the sign before. 

Few references:
https://www.reddit.com/r/AskEurope/comments/23pu36/does_the_euro_sign_go_before_or_after_the_number/
https://www.quora.com/Does-the-euro-symbol-go-ahead-of-the-number-300-or-behind-it-300-I-always-write-it-the-second-way-but-Im-not-sure-Im-right
https://en.wikipedia.org/wiki/Language_and_the_euro#Summary

2021-02-03 14:41 UTC, BenjaminVanRyseghem requested changes

2021-02-03 14:41 UTC, BenjaminVanRyseghem commented on CHANGELOG.md
> +- Fix #569: Fix issue with en-IE currency
Still missing the `Thanks to ...` at the end :smile:

2021-02-03 14:42 UTC, BenjaminVanRyseghem commented
Thanks for the correction.

Could you please rebase your commits so that there are only 2:
- one with the code and the changelog
- one with the AUTHORS

thanks!

2021-02-03 19:33 UTC, BenjaminVanRyseghem commented
One test failed:

```
 en-IE formats currency correctly

    Expected '-€1000.23' to be '€-1000.23', 'Should format currency correctly -1000.234 with $0.00'.
```

2021-02-03 20:01 UTC, Blackbaud-WesGabbard commented
My bad, long day. I should have at least made sure the unit tests passed locally before pushing up.

2021-02-04 08:21 UTC, BenjaminVanRyseghem commented
you removed `package-lock.json`. Could you put it back? :smile:

2021-04-22 13:10 UTC, stephenmcbride commented
@Blackbaud-WesGabbard any chance you could re-visit this PR to make the changes requested? As an Irish dev I'm keen to see it merged 😄

2021-04-29 15:55 UTC, Blackbaud-WesGabbard commented
@stephenmcbride @BenjaminVanRyseghem closing out and moving to https://github.com/BenjaminVanRyseghem/numbro/pull/597

2021-04-29 15:55 UTC, closed without merging