Support specifying trimMantissa with the old string format
BenjaminVanRyseghem/numbro pull request #571
Opened 2020-09-29 15:52 UTC by lexanth

Currently there is no way to convey `trimMantissa` when using the old string format.

Numeral uses square brackets around decimals to convey that these are optional, so use that.

A more complete change would be extending numbro to support a min and max range of mantissa values, but that seems like a much more involved change and this would unblock our migration from numeral to numbro.

2020-10-05 22:38 UTC, BenjaminVanRyseghem requested changes
Thanks a lot :smile:

Could you please add yourself in the AUTHORS file, as well as add a line in CHANGELOG.md?

2020-10-05 22:38 UTC, BenjaminVanRyseghem commented on src/parsing.js
> +            result.trimMantissa = mantissa.indexOf("[") !== -1;
could you please extract this in a separate method please?

I would like to keep a one-to-one option/parsing function to keep things more separated :smile:

2020-10-06 08:17 UTC, lexanth commented
> Thanks a lot 😄
> 
> Could you please add yourself in the AUTHORS file, as well as add a line in CHANGELOG.md?

@BenjaminVanRyseghem all done!

2020-10-06 08:33 UTC, BenjaminVanRyseghem approved these changes

2020-10-06 08:34 UTC, BenjaminVanRyseghem commented
thanks a lot!

@all-contributors please add @lexanth  for code and bug

2020-10-06 08:34 UTC, merged

2020-10-06 08:36 UTC, BenjaminVanRyseghem commented
Adds @lexanth as a contributor for code, bug.

2020-10-12 10:57 UTC, lexanth commented
@BenjaminVanRyseghem any idea when you're going to do another release with this included?